[build]
  publish = "netlify-frontend"
  functions = "netlify/functions"
  command = "echo 'Static site with serverless functions'"

[[redirects]]
  from = "/api/sessions/folder"
  to = "/.netlify/functions/create-session-folder"
  status = 200

[[redirects]]
  from = "/api/sessions"
  to = "/.netlify/functions/create-session"
  status = 200

[[redirects]]
  from = "/api/sessions/:sessionUrl"
  to = "/.netlify/functions/get-session/:sessionUrl"
  status = 200

[[redirects]]
  from = "/api/sessions/:sessionUrl/insights"
  to = "/.netlify/functions/get-insights/:sessionUrl/insights"
  status = 200

[[redirects]]
  from = "/api/sessions/:sessionUrl/analysis"
  to = "/.netlify/functions/get-analysis/:sessionUrl/analysis"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Access-Control-Allow-Origin = "*"
